name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
          
  call-resusable-workflow:
    uses: ./.github/workflows/resusable-workflow.yml
    with:
      node: 14
